[package]
name = "xprite-wasm"
version = "0.1.0"
authors = ["Ricky Han <rickylqhan@gmail.com>"]
edition = "2018"

[dependencies]
stdweb = "0.4.10"
serde = "1.0.71"
serde_derive = "1.0.71"
itertools = "0.7"
xprite = { path = "../xprite" }