language: rust

before_install:
  - sudo apt-get install -y libgtk3-dev

rust:
  - nightly

os:
  - windows
  - linux
  - osx

matrix:
  fast_finish: true

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

addons:
  apt:
    sources:
      - deadsnakes # source required so it finds the package definition below
    packages:
      - python3.5
