[package]
name = "xprite-web"
version = "0.1.0"
authors = ["Ricky Han <rickylqhan@gmail.com>"]
edition = "2018"

[dependencies]
stdweb = "0.4.12"
serde = "1.0.71"
serde_derive = "1.0.71"

[dependencies.xprite]
path = "../xprite"
default-features = false
features = []
